version: '2.1'
services:
  service_a:
    build:
      context: .
      dockerfile: integration_tests/Dockerfile
    ports:
      - "3001:3000"
    command: sh -c "python service_a/app.py"
    healthcheck:
      test: ["CMD", "curl", "-H", "Accept: text/html", "http://127.0.0.1:3000/graphql"]
      interval: 5s
      timeout: 10s
      retries: 10

  service_b:
    build:
      context: .
      dockerfile: integration_tests/Dockerfile
    ports:
      - "3002:3000"
    command: sh -c "python service_b/app.py"
    healthcheck:
      test: ["CMD", "curl", "-H", "Accept: text/html", "http://127.0.0.1:3000/graphql"]
      interval: 5s
      timeout: 10s
      retries: 10

  service_c:
    build:
      context: .
      dockerfile: integration_tests/Dockerfile
    ports:
      - "3003:3000"
    command: sh -c "python service_c/app.py"
    healthcheck:
      test: ["CMD", "curl", "-H", "Accept: text/html", "http://127.0.0.1:3000/graphql"]
      interval: 5s
      timeout: 10s
      retries: 10

  service_d:
    build:
      context: .
      dockerfile: integration_tests/Dockerfile
    ports:
      - "3004:3000"
    command: sh -c "python service_d/app.py"
    healthcheck:
      test: ["CMD", "curl", "-H", "Accept: text/html", "http://127.0.0.1:3000/graphql"]
      interval: 5s
      timeout: 10s
      retries: 10

  federation:
    build: integration_tests/federation
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "-XGET", "http://localhost:3000/.well-known/apollo/server-health"]
      interval: 3s
      timeout: 10s
      retries: 5
    depends_on:
      service_a:
        condition: service_healthy
      service_b:
        condition: service_healthy
      service_c:
        condition: service_healthy
      service_d:
        condition: service_healthy

  test:
    build: integration_tests/tests
    command: sh -c "pytest ./src"
    depends_on:
      federation:
        condition: service_healthy